on:
  workflow_call: {}
jobs:
  deploy_repo:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: deps
        run: |
          echo '${{ secrets.private_gpg }}' | gpg --import
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: write metadata
        run: |
          mkdir ./deploy/repo
          ostree init --mode=archive-z2 --repo ./deploy/repo
          for dir in ./artifacts/* ; do
            mkdir -p $dir/refs/remotes $dir/refs/mirrors
            touch $dir/refs/remotes/.gitkeep $dir/refs/mirrors/.gitkeep
            ostree --repo=./deploy/repo pull-local $dir
          done
          flatpak build-update-repo --gpg-sign=gmankab@gmail.com ./deploy/repo
      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          force_orphan: true
